# Generated by Django 5.1 on 2024-09-18 12:53

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userfiles_cleaned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfiles',
            name='file',
            field=models.FileField(upload_to="files/", verbose_name='File'),
        ),
    ]